version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"
  jobs:
    create_environment:
       - asdf plugin add uv
       - asdf install uv latest
       - asdf global uv latest
       - uv venv
    install:
       - uv pip install -r requirements.txt
    build:
       html:
          - NO_COLOR=1 uv run mkdocs build --strict --site-dir $READTHEDOCS_OUTPUT/html

mkdocs:
  configuration: docs/mkdocs.yml
